### ISSUE TITLE
SpinLock 逻辑问题

### ISSUE THREAD

**Issue by fucktx** [Spongecaptain/redisLock#1]
```
func (lock *RedisLock) SpinLock(times int) error {
	for i := 0; i < times; i++ {
		success, err := lock.TryLock()
		if err != nil {
			return err
		}
		if success {
			return nil
		}
		time.Sleep(time.Millisecond * DefaultSpinInterval)
	}
	return fmt.Errorf("max spin times reached")
}
```

这个逻辑不是for多次去获取锁嘛，if err != nil { return err},这里相当于直接返回了 ，很大程度上没用吧，我理解的为嘛不是 

```
func (lock *RedisLock) SpinLock(times int) error {
	for i := 0; i < times; i++ {
		success, err := lock.TryLock() 
      
               if err == nil && success{
                      return nil
               }
		time.Sleep(time.Millisecond * DefaultSpinInterval)
	}
	return fmt.Errorf("max spin times reached")
}


```

**Comment by wathenjiang** [comment]
这是出于区分如下几个概念：
- 获取到分布式锁
- 未能获取到分布式锁
- 执行出错：例如网络问题

未获取到锁资源实际上是分布式锁的一种正常的逻辑，程序运行没有出错，只是没有获取到锁资源。也就是说如果没有获取到锁资源且没遇到诸如网络错误的问题，err 为 nil，success 为 false。

你的写法可能会隐藏 TryLock 调用中的 error 问题，我的看法是关于此 error 应当交给调用者来决定处理，而不是隐藏。

**Comment by fucktx** [comment]
@Spongecaptain 会隐藏 TryLock 调用中的 error 问题，我的看法是关于此 error 应当交给调用者来决定处理，那这样的话，直接调用TryLock就OK了，这个api其实就有点多余了吧，就你所说的这些情况，其实可以加一个标记error判断处理下就OK，比如 定义 未获取到锁资源  var EmptyError xxx  然后在这里针对特定情况去处理下，而且自旋锁的作用是尽可能的去获取到锁吧

**Comment by wathenjiang** [comment]
> @Spongecaptain 会隐藏 TryLock 调用中的 error 问题，我的看法是关于此 error 应当交给调用者来决定处理，那这样的话，直接调用 TryLock 就 OK 了，这个 api 其实就有点多余了吧，就你所说的这些情况，其实可以加一个标记 error 判断处理下就 OK，比如 定义 未获取到锁资源 var EmptyError xxx 然后在这里针对特定情况去处理下，而且自旋锁的作用是尽可能的去获取到锁吧

你只能返回一个 error，多个 error 还是会被覆盖。出现 error 是少数情况，SpinLock 是服务于自旋锁正常失败后重试，而不是出错失败后重试。
